/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FarmerRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "farmers"
      | "isFarmerRegistered"
      | "owner"
      | "registerFarmer"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateFarmer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "FarmerRegistered" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "farmers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isFarmerRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerFarmer",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFarmer",
    values: [string, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "farmers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isFarmerRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerFarmer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFarmer",
    data: BytesLike
  ): Result;
}

export namespace FarmerRegisteredEvent {
  export type InputTuple = [
    farmer: AddressLike,
    latitude: string,
    longitude: string,
    cropType: string
  ];
  export type OutputTuple = [
    farmer: string,
    latitude: string,
    longitude: string,
    cropType: string
  ];
  export interface OutputObject {
    farmer: string;
    latitude: string;
    longitude: string;
    cropType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FarmerRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): FarmerRegistry;
  waitForDeployment(): Promise<this>;

  interface: FarmerRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  farmers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string] & {
        wallet: string;
        latitude: string;
        longitude: string;
        cropType: string;
      }
    ],
    "view"
  >;

  isFarmerRegistered: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerFarmer: TypedContractMethod<
    [_latitude: string, _longitude: string, _cropType: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateFarmer: TypedContractMethod<
    [_latitude: string, _longitude: string, _cropType: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "farmers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string] & {
        wallet: string;
        latitude: string;
        longitude: string;
        cropType: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isFarmerRegistered"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerFarmer"
  ): TypedContractMethod<
    [_latitude: string, _longitude: string, _cropType: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateFarmer"
  ): TypedContractMethod<
    [_latitude: string, _longitude: string, _cropType: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FarmerRegistered"
  ): TypedContractEvent<
    FarmerRegisteredEvent.InputTuple,
    FarmerRegisteredEvent.OutputTuple,
    FarmerRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "FarmerRegistered(address,string,string,string)": TypedContractEvent<
      FarmerRegisteredEvent.InputTuple,
      FarmerRegisteredEvent.OutputTuple,
      FarmerRegisteredEvent.OutputObject
    >;
    FarmerRegistered: TypedContractEvent<
      FarmerRegisteredEvent.InputTuple,
      FarmerRegisteredEvent.OutputTuple,
      FarmerRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
